[package]
name = "cozip_win_installer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "cozip_win_installer"
path = "src/main.rs"

[[bin]]
name = "cozip_win_uninstaller"
path = "src/bin/cozip_win_uninstaller.rs"

[dependencies]
gpui = "0.2.2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Globalization", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_LibraryLoader", "Win32_System_Registry", "Win32_System_Threading", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }


[build-dependencies]
embed-resource = "3.0.6"
